version: "3.8"
services:
  backend:
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/app/backend
      - backend_node_modules:/app/backend/node_modules
    ports:
      - "9000:9000"
      - "7001:7001"

  storefront:
    volumes:
      - ./storefront:/app/storefront
      - storefront_node_modules:/app/storefront/node_modules
    ports:
      - "8000:8000"

volumes:
  storefront_node_modules:
  backend_node_modules:
